CREATE TABLE lists (
  id int PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name text UNIQUE NOT NULL
);

CREATE TABLE todos (
  id int PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name text NOT NULL,
  list_number int NOT NULL REFERENCES lists(id) ON DELETE CASCADE,
  completed boolean NOT NULL DEFAULT false
);